package com.gxp.mapper;

import com.gxp.model.BookType;

public interface BookTypeMapper extends BookTypeBaseMapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktypes
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktypes
     *
     * @mbg.generated
     */
    int insert(BookType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktypes
     *
     * @mbg.generated
     */
    int insertSelective(BookType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktypes
     *
     * @mbg.generated
     */
    BookType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktypes
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BookType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktypes
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BookType record);

}